version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.12.0

    working_directory: ~/react-searchable

    steps:
      - checkout
      - restore_cache:
          name: Restore dependencies
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Caching dependencies
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Testing
          command: yarn test -u
      - run:
          name: Uploading code coverage
          command: yarn codecov
