version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.12.0

    working_directory: ~/react-searchable

    steps:
      - checkout
      - restore_cache:
          name: Restore dependencies
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Caching dependencies
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Set up Code Climate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Testing
          command: |
            ./cc-test-reporter before-build
            yarn test -u
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
